apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rlbet7klg-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rlbet7klg-python 
  name: rlbet7klg-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rlbet7klg-python 
