apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rlbet7klg-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/chetna14manku_org/rhtap-qe-python:github-ecd8067b14d6f811f078ff68b1c9e37edcd947e9
          name: container-image
